config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  # get 'sessions/new'

  # get 'static_pages/home'

  get '/help',    to: 'static_pages#help'
  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup',  to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :posts
  resources :users
  resources :comments

  root 'static_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 140 }
  validates :content, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :set_post, only: :show
    before_action :logged_in_user, only: [:new, :create, :destroy]
    before_action :correct_user, only: [:edit, :update, :destroy]

    def index
        redirect_to root_url
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
        email = current_user.email if !!current_user
        @comment = @post.comments.build(post_id: @post.id, email: email)
        @comments = @post.comments.paginate(page: params[:page])
    end

    def new
        @post = current_user.posts.build
    end

    def create
        @post = current_user.posts.build(post_params)
        if @post.save
            flash[:success] = "Post created!"
            redirect_to root_url
        else
            render new_post_path
        end
    end

    # GET /posts/1/edit
    def edit
        @post = Post.find(params[:id])
    end

    # PATCH/PUT /posts/1
    # PATCH/PUT /posts/1.json
    def update
        respond_to do |format|
            if @post.update(post_params)
                flash[:success] = 'Post was successfully updated.'
                format.html { redirect_to root_url }
            else
                format.html { render 'edit' }
            end
          end
    end
    
    def destroy
        @post.destroy
        flash[:success] = "Post deleted."
        redirect_back(fallback_location: root_url)
    end

    private
        def correct_user
            @post = current_user.posts.find_by(id: params[:id])
            redirect_to root_url if @post.nil?
        end

        def set_post
            @post = Post.find(params[:id])
        end

        def post_params
            params.require(:post).permit(:content, :title)
        end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_edit.html.erb
<div class="row">
    <aside class="col-md-12">
        <section class="user_info">
            <%= render 'shared/user_info' %>
        </section>
        <section class="post_form">
            <%= render 'shared/post_form' %>
        </section>
    </aside>
</div>

<script>
//jQuery实现textarea高度根据内容自适应
$.fn.extend({
    txtaAutoHeight: function () {
        return this.each(function () {
            var $this = $(this);
            if (!$this.attr('initAttrH')) {
                $this.attr('initAttrH', $this.outerHeight());
            }
            setAutoHeight(this).on('input', function () {
                setAutoHeight(this);
            });
        });
        function setAutoHeight(elem) {
            var $obj = $(elem);
            return $obj.css({ height: $obj.attr('initAttrH'), 'overflow-y': 'hidden' }).height(elem.scrollHeight);
        }
    }
});

//调用
$(function () {
    $("#post_content").txtaAutoHeight();
});
</script>

app/views/posts/_post.html.erb
<li id="post-<%= post.id %>">
    <!--%= link_to gravatar_for(post.user, size: 50), post.user %-->
    <!--span class="user"><%= link_to post.user.name, post.user %></span-->
    <span class="title"><h6><%= link_to post.title, post %></h6></span>
    <span class="timestamp">
        <%= link_to post.user.name, post.user %>
         Posted <%= time_ago_in_words(post.created_at) %> ago.
        <% if current_user?(post.user) %>
            <%= link_to "edit", edit_post_path(post) %>
            <%= link_to "delete", post, method: :delete,
                                        data: { confirm: "You sure?" } %>
        <% end %>
    </span>
</li>

app/views/posts/edit.html.erb
<% provide(:title, "Edit") %>

<%= render 'edit' %>

app/views/posts/new.html.erb
<% provide(:title, "New Post") %>

<%= render 'edit' %>

app/views/posts/show.html.erb
<% provide(:title, @post.title) %>

<div class="row">
    <div class="col-md-12">
        <div style="padding-top: 5px; padding-bottom: 12px;">
            <span class="title"><h6><%= @post.title %></h6></span>
            <span class="timestamp">
                <%= link_to @post.user.name, @post.user %>
                Posted <%= time_ago_in_words(@post.created_at) %> ago.
                <% if current_user?(@post.user) %>
                    <%= link_to "edit", edit_post_path(@post) %>
                <% end %>
            </span>
        </div>
        <pre style="word-break: keep-all; word-wrap: break-word; white-space: pre-wrap; white-space: -moz-pre-wrap" ><%= @post.content %></pre>
        <h3>Comments</h3>
        <div class="col-md-6">
            <%= form_for(@comment) do |f| %>
                <%= render 'shared/error_messages', object: f.object %>
                <%= hidden_field_tag :post_id, @post.id %>
                <%= f.label :email %>
                <%= f.email_field :email, class: 'form-control' %>

                <%= f.label :content %>
                <%= f.text_area :content, class: 'form-control' %>

                <%= f.submit "Post", class: "btn btn-primary" %>
            <% end %>
        </div>
        <div class="col-md-6">
            <%# 评论 %>
            <ol class="comments">
                <%= render @comments %>
            </ol>
            <%= will_paginate @comments %>
        </div>
    </div>
</div>